name: My First github action
on: [push] #type of action on which to run the below jobs
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: build the project
        run: yarn build
      - name: setup finish
        run: echo "Hurray!!"
